/** Declaration file generated by dts-gen */
declare module 'chrome-remote-interface' {
  export = chrome_remote_interface;

  declare function chrome_remote_interface(options: any, callback?: any): any;

  declare namespace chrome_remote_interface {
    function Activate(options: any, callback?: any): any;

    function Close(options: any, callback?: any): any;

    function List(options: any, callback?: any): any;

    function New(options: any, callback?: any): any;

    function Protocol(options: any, callback?: any): any;

    function Version(options: any, callback?: any): any;
  }
}
